//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Actions"",
    ""maps"": [
        {
            ""name"": ""Reel"",
            ""id"": ""66f0053b-ec20-4960-978a-844c05336e0c"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""b3e8f563-9f57-4ab6-adf5-80d16fc2bae0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""63fbd7d3-d3f0-49f4-bbd4-5b4e21c693bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""f78ffe52-ebc6-4b60-bcab-568d34605b96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""8409f007-b4de-49e5-a0e8-0060ee62dff8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""587c6673-0cba-4915-9da8-722c82f84d4c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2e74865-f963-4104-b68b-b0ace122a6e2"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9abab48-87e0-45cf-83f7-2341738ce978"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d9aaab2-9b51-4246-9590-d7bb43a425bf"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Fishing"",
            ""id"": ""1c95a321-fdfe-42aa-a248-ba379f9228ea"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Button"",
                    ""id"": ""14735848-96b4-44cd-b925-a9d1d41fa758"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ae7d00bd-036f-4ed1-b9a4-4acb7035a134"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""B"",
            ""id"": ""de630de0-8ee5-4800-9055-e532011f15b1"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""c3518b39-a4f0-4898-a4df-0fa11049dd61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""05f9fd02-3809-4cad-a1d9-a0643d09c6a2"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Xbox"",
            ""bindingGroup"": ""Xbox"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Reel
        m_Reel = asset.FindActionMap("Reel", throwIfNotFound: true);
        m_Reel_Up = m_Reel.FindAction("Up", throwIfNotFound: true);
        m_Reel_Down = m_Reel.FindAction("Down", throwIfNotFound: true);
        m_Reel_Left = m_Reel.FindAction("Left", throwIfNotFound: true);
        m_Reel_Right = m_Reel.FindAction("Right", throwIfNotFound: true);
        // Fishing
        m_Fishing = asset.FindActionMap("Fishing", throwIfNotFound: true);
        m_Fishing_Movement = m_Fishing.FindAction("Movement", throwIfNotFound: true);
        // B
        m_B = asset.FindActionMap("B", throwIfNotFound: true);
        m_B_Newaction = m_B.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Reel
    private readonly InputActionMap m_Reel;
    private IReelActions m_ReelActionsCallbackInterface;
    private readonly InputAction m_Reel_Up;
    private readonly InputAction m_Reel_Down;
    private readonly InputAction m_Reel_Left;
    private readonly InputAction m_Reel_Right;
    public struct ReelActions
    {
        private @InputActions m_Wrapper;
        public ReelActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_Reel_Up;
        public InputAction @Down => m_Wrapper.m_Reel_Down;
        public InputAction @Left => m_Wrapper.m_Reel_Left;
        public InputAction @Right => m_Wrapper.m_Reel_Right;
        public InputActionMap Get() { return m_Wrapper.m_Reel; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ReelActions set) { return set.Get(); }
        public void SetCallbacks(IReelActions instance)
        {
            if (m_Wrapper.m_ReelActionsCallbackInterface != null)
            {
                @Up.started -= m_Wrapper.m_ReelActionsCallbackInterface.OnUp;
                @Up.performed -= m_Wrapper.m_ReelActionsCallbackInterface.OnUp;
                @Up.canceled -= m_Wrapper.m_ReelActionsCallbackInterface.OnUp;
                @Down.started -= m_Wrapper.m_ReelActionsCallbackInterface.OnDown;
                @Down.performed -= m_Wrapper.m_ReelActionsCallbackInterface.OnDown;
                @Down.canceled -= m_Wrapper.m_ReelActionsCallbackInterface.OnDown;
                @Left.started -= m_Wrapper.m_ReelActionsCallbackInterface.OnLeft;
                @Left.performed -= m_Wrapper.m_ReelActionsCallbackInterface.OnLeft;
                @Left.canceled -= m_Wrapper.m_ReelActionsCallbackInterface.OnLeft;
                @Right.started -= m_Wrapper.m_ReelActionsCallbackInterface.OnRight;
                @Right.performed -= m_Wrapper.m_ReelActionsCallbackInterface.OnRight;
                @Right.canceled -= m_Wrapper.m_ReelActionsCallbackInterface.OnRight;
            }
            m_Wrapper.m_ReelActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Up.started += instance.OnUp;
                @Up.performed += instance.OnUp;
                @Up.canceled += instance.OnUp;
                @Down.started += instance.OnDown;
                @Down.performed += instance.OnDown;
                @Down.canceled += instance.OnDown;
                @Left.started += instance.OnLeft;
                @Left.performed += instance.OnLeft;
                @Left.canceled += instance.OnLeft;
                @Right.started += instance.OnRight;
                @Right.performed += instance.OnRight;
                @Right.canceled += instance.OnRight;
            }
        }
    }
    public ReelActions @Reel => new ReelActions(this);

    // Fishing
    private readonly InputActionMap m_Fishing;
    private IFishingActions m_FishingActionsCallbackInterface;
    private readonly InputAction m_Fishing_Movement;
    public struct FishingActions
    {
        private @InputActions m_Wrapper;
        public FishingActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Fishing_Movement;
        public InputActionMap Get() { return m_Wrapper.m_Fishing; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FishingActions set) { return set.Get(); }
        public void SetCallbacks(IFishingActions instance)
        {
            if (m_Wrapper.m_FishingActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_FishingActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_FishingActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_FishingActionsCallbackInterface.OnMovement;
            }
            m_Wrapper.m_FishingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
            }
        }
    }
    public FishingActions @Fishing => new FishingActions(this);

    // B
    private readonly InputActionMap m_B;
    private IBActions m_BActionsCallbackInterface;
    private readonly InputAction m_B_Newaction;
    public struct BActions
    {
        private @InputActions m_Wrapper;
        public BActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_B_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_B; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BActions set) { return set.Get(); }
        public void SetCallbacks(IBActions instance)
        {
            if (m_Wrapper.m_BActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_BActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_BActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_BActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_BActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public BActions @B => new BActions(this);
    private int m_XboxSchemeIndex = -1;
    public InputControlScheme XboxScheme
    {
        get
        {
            if (m_XboxSchemeIndex == -1) m_XboxSchemeIndex = asset.FindControlSchemeIndex("Xbox");
            return asset.controlSchemes[m_XboxSchemeIndex];
        }
    }
    public interface IReelActions
    {
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
    }
    public interface IFishingActions
    {
        void OnMovement(InputAction.CallbackContext context);
    }
    public interface IBActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
