//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Actions"",
    ""maps"": [
        {
            ""name"": ""Reel"",
            ""id"": ""66f0053b-ec20-4960-978a-844c05336e0c"",
            ""actions"": [
                {
                    ""name"": ""ReelAction"",
                    ""type"": ""Button"",
                    ""id"": ""b3e8f563-9f57-4ab6-adf5-80d16fc2bae0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""587c6673-0cba-4915-9da8-722c82f84d4c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReelAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e49afc8-3640-4881-a65e-c84ea7cdc196"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReelAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5442968-066a-4902-a7d8-660fe147b76f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReelAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""856dc100-7544-47c5-bc6e-2851c6f2093d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReelAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Xbox"",
            ""bindingGroup"": ""Xbox"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Reel
        m_Reel = asset.FindActionMap("Reel", throwIfNotFound: true);
        m_Reel_ReelAction = m_Reel.FindAction("ReelAction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Reel
    private readonly InputActionMap m_Reel;
    private IReelActions m_ReelActionsCallbackInterface;
    private readonly InputAction m_Reel_ReelAction;
    public struct ReelActions
    {
        private @InputActions m_Wrapper;
        public ReelActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ReelAction => m_Wrapper.m_Reel_ReelAction;
        public InputActionMap Get() { return m_Wrapper.m_Reel; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ReelActions set) { return set.Get(); }
        public void SetCallbacks(IReelActions instance)
        {
            if (m_Wrapper.m_ReelActionsCallbackInterface != null)
            {
                @ReelAction.started -= m_Wrapper.m_ReelActionsCallbackInterface.OnReelAction;
                @ReelAction.performed -= m_Wrapper.m_ReelActionsCallbackInterface.OnReelAction;
                @ReelAction.canceled -= m_Wrapper.m_ReelActionsCallbackInterface.OnReelAction;
            }
            m_Wrapper.m_ReelActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ReelAction.started += instance.OnReelAction;
                @ReelAction.performed += instance.OnReelAction;
                @ReelAction.canceled += instance.OnReelAction;
            }
        }
    }
    public ReelActions @Reel => new ReelActions(this);
    private int m_XboxSchemeIndex = -1;
    public InputControlScheme XboxScheme
    {
        get
        {
            if (m_XboxSchemeIndex == -1) m_XboxSchemeIndex = asset.FindControlSchemeIndex("Xbox");
            return asset.controlSchemes[m_XboxSchemeIndex];
        }
    }
    public interface IReelActions
    {
        void OnReelAction(InputAction.CallbackContext context);
    }
}
